Bellettrie/library_system

datamining/views.py
lendings/procedures/extend.py
lendings/tests.py
reservations/procedures/new_reservation.py

Added check to assert_member_can_lend_item and removed check whether borrower is same as person that wants to reserve

Members are not allowed to reserve books they have borrowed

---

bellettrie_library_system/settings.py
members/views/user/invite_code_generate.py

This fix is already in-use on production, but needs to move into the codebase as well.

Fix issue with invite code links

---

lendings/views/me.py

Change PermissionRequiredMixin to LoginRequiredMixin because of normal users that cannot see the list

Change PermissionRequiredMixin to LoginRequiredMixin

---

series/templates/series/view.html
tables/templates/columns/title_column.html
works/models.py
works/templates/works/detail.html

Add articles when displaying the original titles of books.

---

members/views/member_list.py

fixed memberlist pagination by ordering by member id.

---

creators/templates/creators/creator_view.html

Removed superfluous author name from author page

---

members/templates/users/create.html

added comment to user create for clarity

---

members/templates/users/delete.html
members/views/user/delete.py
members/views/user/edit.py

Fix member link on user edit

---

lendings/templates/lendings/detail.html
lendings/urls.py
lendings/views/me.py
tables/templatetags/member_reservation_table.py

Added reserveations to the me page

---

tables/buttons.py

Added new non reservable status messages

---

works/views.py

Removing authors from a book or a book from a series caused a crash of the site.

Fixed an error on save because of save behaviour

---

.github/workflows/continuous_integration_tests.yml
bellettrie_library_system/settings.py
public_pages/views.py

Resolves #525 and updates pipeline setup

Switch CI to postgreql, remove the option to run with sqlite or mysql.

---

lendings/views/lending_history.py
tables/buttons.py
tables/templates/buttons/lend_history_button.html
tables/templatetags/item_detail_table.py
works/templates/works/detail.html

Fixed lending history to be per item instead of by work.

---

bellettrie_library_system/settings.py
requirements.txt
requirements_production.txt

Psycopg3 test

---

members/templates/members/detail.html
members/templates/members/detail_shortened.html

Add newlines to member notes

---

lendings/views/register_returned.py
members/views/user/invite_code_generate.py

Cleanup detailed/undetailed member page referrals

---

datamining/procedures/filter_members.py
datamining/templates/datamining/member_filtering.html
datamining/views.py

Changed member filtering to use only one date

---

tables/templates/buttons/reserve_item_button.html

"For Other" button consistent between the enabled and disabled state

---

lendings/templates/lendings/return_book.html
lendings/views/register_returned.py

Added a bootstrap card layout to the reservation return page

---

creators/templatetags/creator_books.py
creators/views.py

Added publication to creator when subwork is by creator

---

lendings/templates/lendings/return_book_hx.html
lendings/templates/lendings/returned_book_hx.html
lendings/urls.py
lendings/views/register_returned.py
tables/templates/buttons/return_item_button.html

Using HTMX with a modal for returning books

Hx return book

---

members/urls.py
members/views/auth/by_committee.py

Made an end point that checks if the user is in the Web Committee

---

creators/models.py
members/models/member.py
series/models.py
works/models.py

Changed how models deal with unsaved models instances

---

requirements.txt
requirements_production.txt

Tested quite extensively on staging; no issues found

Update to django 5.1

---

works/components/works/table/card.html
works/components/works/table/row.html

#663 In tailwind version of UI, add <no Title> kinda thing to works/components/works/info_card.html if book has no title

---

members/models/membership_period.py
members/templates/members/edit.html
members/views/member_new.py

Fixed a few errors in member creation
